spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reactiveDb?serverZoneId=Asia/Kolkata
    username: root
    password: Pranav@123

  flyway:
    url: jdbc:mysql://localhost:3306/reactiveDb
    user: root
    password: Pranav@123